### ISSUE TITLE
1.19.2?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [ugackMiner53/DiscordProximity#2]
I know asking for a backport is generally a bit hard to do and not many people like doing so but I was wondering if it'd be possible to do?

**Comment by ugackMiner53** [comment]
(Completed in the 1.0.1 release [[commit](https://github.com/ugackMiner53/DiscordProximity/commit/1608924345953d8bb39149d8a14128801c90a554)])

**Comment by Aces-and-Jacks** [comment]
Thanks
